env:
  browser: true
  es6: true
  jest: true
  node: true

extends: 'eslint:recommended'

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 8
  sourceType: module

rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - 0
  no-multiple-empty-lines:
    - warn
  max-len:
    - 1
    - 100
